### PR TITLE
Added Powerlimit support + parameterized addresses

### PR DESCRIPTION
**Pull request by StefanFabian**
As discussed in #92, this PR adds support to set and read the power limits P1 and P2.
Since this added more addresses, I've moved the addresses from hardcoded to a separate named tuple with the option to add support for CPUs where the MSR addresses differ (though I don't know of any where this is the case).

### CODE REVIEW

**Comment by georgewhewell** [comment]
Looks good, thanks! I don't think this MSR addresses will change (and if they do probably architecture will be different enough to make a new tool), so could you revert that bit? Have not had a chance to test yet but will try to ASAP.

**Comment by StefanFabian** [comment]
I can remove the option but I would suggest keeping the named tuple to make it more readable and less error prone than using raw adresses.

**Comment by georgewhewell** [comment]
@StefanFabian yes that sounds good!

**Comment by steffensol** [comment]
HI, any work ongoing to get this merged in? I would really want the functionality available in the standard pip-install

**Comment by StefanFabian** [comment]
Ah sorry, forgot about this PR. I've removed the cpu option now.

**Pull request merged**
