### PR TITLE
make it so this runs modprobe msr automatically.

### PR DESCRIPTION
**Pull request by oscardssmith**
Does this need error checking?

### CODE REVIEW

**Comment by georgewhewell** [comment]
Thanks! Could you put it behind `if not glob('/dev/cpu/*/msr'):` so it doesn't get run unnecessarily? I don't think there is much error checking worth doing- perhaps change `call` to `check_call`, so we exit with exception if module cannot be loaded.

**Comment by oscardssmith** [comment]
that makes sense. I'll update the pr.

**Comment by oscardssmith** [comment]
Should be ready to merge.

**Comment by georgewhewell** [comment]
thanks!

**Pull request merged**
