### PR TITLE
change method for fetching CPU core count

### PR DESCRIPTION
**Pull request by ghost**
pipes output of `lscpu` into variable and parses output of line
'NUMA node0 CPU(s):' to get currently available CPUs, which provides
correctly available CPUs even when hyperthreading is disabled.

previous method multiprocessing.cpu_count() returns all available
cores including logical, even if disabled -- causing write_msr()
function to fail if cores are disabled via kernel boot parameters

Signed-off-by: kim (grufwub) <grufwub@gmail.com>

### CODE REVIEW

**Comment by georgewhewell** [comment]
Thanks for PR! This is second attempt at fixing issues when cpu count != /dev/msr node count (see #12). I wonder whether we should just drop this assumption altogether and try to write to as many nodes as we can see and throw exception if none succeed?

**Comment by StefanFabian** [comment]
This will not work on all systems.
On my system `lscpu` prints:
```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
...
NUMA node0 CPU(s):   0-7
...
```
This script seems to assume that all numbers are listed, e.g., `0,1,2,3`.
Wouldn't it make way more sense to include a check such as
```
os.path.isdir("/dev/cpu/X")
```
This would also not require calling a different process which is not something you should do unless absolutely necessary.

**Comment by ghost** [comment]
> This will not work on all systems.
> On my system `lscpu` prints:
> 
> ```
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              8
> On-line CPU(s) list: 0-7
> Thread(s) per core:  2
> Core(s) per socket:  4
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> ...
> NUMA node0 CPU(s):   0-7
> ...
> ```
> 
> This script seems to assume that all numbers are listed, e.g., `0,1,2,3`.
> Wouldn't it make way more sense to include a check such as
> 
> ```
> os.path.isdir("/dev/cpu/X")
> ```
> 
> This would also not require calling a different process which is not something you should do unless absolutely necessary.

this sounds like the best method. I'll get on this later today and modify the branch

**Comment by ghost** [comment]
Added this change @StefanFabian's change, what do you think @georgewhewell?

**Comment by StefanFabian** [comment]
Don't want to be pedantic (since it's not my repo) but it seems like a simpler change would be in the original for loop to add an
```python
if not os.path.isdir(...):
    continue
```

Either way, it should probably also have a mechanism, e.g., a boolean, to indicate whether any core was processed. If not a single core was processed, it should be reported as an error as @georgewhewell suggested.

**Comment by georgewhewell** [comment]
Thanks @grufwub @StefanFabian. works for me, i merged and will push new release. if this problem occurs again we can rework error handling as discussed

**Pull request merged**
